### ISSUE TITLE
The prediction for images sequence

### ISSUE THREAD

**Issue by kxgy2018** [sremes/nonstationary-spectral-kernels#3]
Hello! Thank you for your help.

I would like to know if the code for 2D image sequence prediction can be provided？ Because there is only code for one-dimensional time sequence prediction can be found.

**Comment by sremes** [comment]
Hi @kxgy2018, sorry for the late reply! You can use the code here for multidimensional grids like 2D images over time, which is a 3D grid. Have a look at the last example in the README, using the Kronecker product inference.

**Comment by kxgy2018** [comment]
Thanks a lot for your help, but I'm having trouble running the code like below
`hyp = init_kron(x, A, hyp_kernel, noise_var, max_freq); % random initialization with A components`

How can I get the value of hyp_kernel, noise_var, and max_freq? If I use the function 'get_hyp_kernel' to obtain the value of hyp_kernel, an error will occur because the function 'gausskernel.m' cannot handle high-dimensional inputs. I wonder if it is possible to provide a code demo for high-dimensional input, just like the test_simulated.m in the source code.

Best regards!
